main/urls.py
from django.urls import path
from . import views
from .views import ImageListView, ImageCreateView


urlpatterns = [
    path('', views.home, name="home"),
    path('images/', ImageListView.as_view(), name="images_list"),
    path('images/new/', ImageCreateView.as_view(), name="add_images"),
]

minpix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from PIL import Image
import PIL
from django.utils import timezone
from django.urls import reverse



# Create your models here.

class IMage(models.Model):
	title = models.CharField(max_length=50, null=True)
	image_file = models.ImageField(default='default.jpg', upload_to='images/')
	date_added = models.DateTimeField(default=timezone.now)

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)

		img = Image.open(self.image_file.path)
		new_width = img.size[0]
		new_height = img.size[1]
		img = img.resize((new_width,new_height), PIL.Image.ANTIALIAS)
		img.save(self.image_file.path)


	def __str__(self):
		return self.title


	def get_absolute_url(self):
		return reverse('images_list')

main/views.py
from django.shortcuts import render
from .models import IMage
from django.views.generic import ListView, CreateView

# Create your views here.


def home(request):
	return render(request, 'main/home.html')



class ImageListView(ListView):
	model = IMage
	template_name = 'main/image_list.html'
	context_object_name = 'IMage'
	ordering = ['-date_added']
	
class ImageCreateView(CreateView):
	model = IMage
	fields = ['title', 'image_file']
	

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}"/>
    <link rel="stylesheet" type="text/JavaScript" href="{% static 'main/form.js' %}"/>

	{% if title %}
    <title>MinPix - {{ title }}</title>
  {% else %}
    <title>MinPix</title>
  {% endif %}


  </head>
  <body>
    <div class="container-fluid banner">
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar navbar-md">
            <a class="navbar-brand mr-4" href="{% url 'home' %}">MinPix</a>
            <ul class="nav">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'home' %}">HOME</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'add_images' %}">ADD</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'images_list' %}">LIBRARY</a>
              </li>
             
            </ul>
            
          </nav>
        </div>

    <div class="container">
      {% block content %}     {% endblock %}
    </div>


    

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

main/templates/main/home.html
{% extends "main/base.html" %}
{% block content %}
 <!-- The slideshow -->
 <div class="col-md-8 offset-md-2 info">
	<p class="text-center">
		Click 'Add Image' to add images to your library
	</p>
	<a href="{% url 'add_images' %}" class="btn btn-md text-center">ADD IMAGE</a>
</div>
{% endblock content %}

main/templates/main/image_add.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<center>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Upload Image</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Upload</button>
            </div>
        </form>
     </div>
</center>
{% endblock content %}

main/templates/main/image_form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-groupf">
            <h2>UPLOAD IMAGE</h2>
            <p><label class="title" for="id_title">Title:</label>
                <input class="text-name" type="text" name="title" maxlength="50" required id="id_title">
            </p>
            <p><label class="imagefile" for="id_image_file">Image file:</label>
                <input class="openfile" type="file" name="image_file" accept="image/*" id="id_image_file">
            </p>
            <div class="form-group">
                <input type="submit" value="Save">
            </div>
        </fieldset>

    </form>
</div>
{% endblock content %}

main/templates/main/image_list.html
{% extends "main/base.html" %}
{% block content %}
	
	<h1>Your Library</h1>
	{% for image in IMage %}

	<article class="media content-section">
		<div class="media-body">
			<div class="article-metadata">
				{{ image.title }}
				<small class="text-muted">{{ image.date_added }}</small>
				<a href="{{ image.image_file.url }}" download="{{ image.image_file }}">Download</a>
			</div>
		</div>
	</article>
	{% endfor %}


{% endblock content %}